baseurl = "https://cloud.gov"
canonifyurls = "true"
relativeurls = "true"
languageCode = "en-us"
title = "cloud.gov"
pluralizelisttitles = "false"
publishdir = "public"

[params]
  email = "cloud-gov-inquiries@gsa.gov"
  description = "cloud.gov documentation"
  author = "18f"

  [params.analytics]
    [params.analytics.google]
      code = "UA-48605964-34"
    [params.analytics.dap]
      agency = "GSA"
      subagency = "18F"

[blackfriday]
  plainIDAnchors = true


[[menu.overview]]
    name = "cloud.gov overview"
    identifier = "overview"
    weight = -120
[[menu.overview]]
    name = "Purchase and pricing"
    identifier = "pricing"
    weight = -115
[[menu.overview]]
    name = "Technology and security"
    identifier = "technology"
    weight = -105
[[menu.overview]]
    name = "Customer stories"
    identifier = "customer-stories"
    weight = -100

[[menu.docs]]
    name = "Getting started"
    identifier = "getting-started"
    pre = "<i class='fa fa-road fa-fw'></i>"
    weight = -120
[[menu.docs]]
    name = "Deploying apps"
    identifier = "apps"
    pre = "<i class='fa fa-file-text fa-fw'></i>"
    weight = -110
[[menu.docs]]
    name = "Services"
    identifier = "services"
    pre = "<i class='fa fa-fw fa-database'></i>"
    weight = -100
[[menu.docs]]
    name = "Managing apps"
    identifier = "advanced"
    pre = "<i class='fa fa-rocket fa-fw'></i>"
    weight = -100
[[menu.docs]]
    name = "Compliance"
    identifier = "compliance"
    pre = "<i class='fa fa-check-square-o fa-fw'></i>"
    weight = -95
[[menu.docs]]
    name = "Experimental features"
    identifier = "experimental"
    pre = "<i class='fa fa-flask fa-fw'></i>"
    weight = -90

[[menu.docs]]
    name = "cloud.gov team docs"
    identifier = "ops"
    pre = "<i class='fa fa-fw fa-wrench'></i>"
[[menu.docs]]
    name = "Deployment"
    identifier = "deployment"
    parent = "ops"
[[menu.docs]]
    name = "Tenant support"
    identifier = "tenants"
    parent = "ops"
[[menu.docs]]
    name = "Operations"
    identifier = "operations"
    parent = "ops"
[[menu.docs]]
    name = "Runbook"
    identifier = "runbook"
    parent = "ops"
[[menu.docs]]
    name = "Plans and policies"
    identifier = "policies"
    parent = "ops"
