baseurl = "https://docs.cloud.gov/"
MetaDataFormat = "yaml"
title = "docs.cloud.gov"

[params]
  description = "Cloud.gov documentation"
  author = "18f"

[[menu.main]]
    name = "Docs"
    identifier = "docs"
    weight = -10
[[menu.main]]
    name = "Getting Started"
    parent = "docs"
    identifier = "getting-started"
    pre = "<i class='fa fa-road'></i>"
    weight = -120
[[menu.main]]
    name = "Deploying Apps"
    parent = "docs"
    identifier = "apps"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -110
[[menu.main]]
    name = "Operations"
    parent = "docs"
    identifier = "ops"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -90
[[menu.main]]
    name = "Standards"
    parent = "docs"
    identifier = "standards"
    pre = "<i class='fa fa-desktop'></i>"
    weight = -85

[[menu.main]]
    name = "Introduction"
    identifier = "intro"
    weight = -20
[[menu.main]]
    name = "Overview"
    parent = "intro"
    identifier = "overview"
    weight = -120
[[menu.main]]
    name = "Pricing"
    parent = "intro"
    identifier = "pricing"
    weight = -115
[[menu.main]]
    name = "Security"
    parent = "intro"
    identifier = "security"
    weight = -110
[[menu.main]]
    name = "Technology"
    parent = "intro"
    identifier = "technology"
    weight = -105
[[menu.main]]
    name = "Terminology"
    parent = "intro"
    identifier = "terminology"
    weight = -100
