baseurl = "https://docs.cloud.gov/"
MetaDataFormat = "yaml"
title = "Documentation"
publishdir = "public"

[params]
  description = "cloud.gov documentation"
  author = "18f"
[blackfriday]
  plainIDAnchors = true

[[menu.main]]
    name = "Introduction"
    identifier = "intro"
    weight = -20
[[menu.main]]
    name = "Overview"
    parent = "intro"
    identifier = "overview"
    weight = -120
[[menu.main]]
    name = "Pricing"
    parent = "intro"
    identifier = "pricing"
    weight = -115
[[menu.main]]
    name = "Security"
    parent = "intro"
    identifier = "security"
    weight = -110
[[menu.main]]
    name = "Technology"
    parent = "intro"
    identifier = "technology"
    weight = -105
[[menu.main]]
    name = "Terminology"
    parent = "intro"
    identifier = "terminology"
    weight = -100

[[menu.main]]
    name = "Usage"
    identifier = "usage"
    weight = -10
[[menu.main]]
    name = "Getting Started"
    parent = "usage"
    identifier = "getting-started"
    pre = "<i class='fa fa-road'></i>"
    weight = -120
[[menu.main]]
    name = "Deploying Apps"
    parent = "usage"
    identifier = "apps"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -110
[[menu.main]]
    name = "Advanced"
    parent = "usage"
    identifier = "advanced"
    pre = "<i class='fa fa-rocket'></i>"
    weight = -100
[[menu.main]]
    name = "Experimental Features"
    parent = "usage"
    identifier = "experimental"
    pre = "<i class='fa fa-flask'></i>"
    weight = -90

[[menu.main]]
    name = "Contributing"
    identifier = "ops"
[[menu.main]]
    name = "Deployment"
    identifier = "deployment"
    parent = "ops"
[[menu.main]]
    name = "Users"
    identifier = "users"
    parent = "ops"
[[menu.main]]
    name = "Operations"
    identifier = "operations"
    parent = "ops"
