baseurl = "https://docs.cloud.gov/"
MetaDataFormat = "yaml"
title = "docs.cloud.gov"

[params]
  description = "Cloud.gov documentation"
  author = "18f"


[[menu.main]]
    name = "Getting Started"
    identifier = "getting-started"
    pre = "<i class='fa fa-road'></i>"
    weight = -120
[[menu.main]]
    name = "Deploying Apps"
    identifier = "apps"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -110
[[menu.main]]
    name = "Operations"
    identifier = "ops"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -90
[[menu.main]]
    name = "Standards"
    identifier = "standards"
    pre = "<i class='fa fa-desktop'></i>"
    weight = -85
