baseurl = "https://cloud.gov"
languageCode = "en-us"
title = "cloud.gov"
pluralizelisttitles = "false"
publishdir = "public"
pygmentsCodeFences = "true"
pygmentsUseClasses = "true"

[params]
  email = "cloud-gov-inquiries@gsa.gov"
  description = "Expedite your agency’s path to a secure and compliant cloud. cloud.gov provides an application environment that enables rapid deployment and ATO assessment for modern web applications."
  author = "18f"

  [params.analytics]
    [params.analytics.google]
      code = "UA-48605964-34"
    [params.analytics.dap]
      agency = "GSA"
      subagency = "18F"

[blackfriday]
  plainIDAnchors = true


[[menu.docs]]
    name = "Overview"
    identifier = "overview"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = -150
[[menu.docs]]
    name = "Purchase and pricing"
    identifier = "pricing"
    pre = "<i class='fa fa-shopping-cart fa-fw'></i>"
    weight = -140
[[menu.docs]]
    name = "Technology and security"
    identifier = "technology"
    pre = "<i class='fa fa-lock fa-fw'></i>"
    weight = -130
[[menu.docs]]
    name = "Customer stories"
    identifier = "customer-stories"
    pre = "<i class='fa fa-users fa-fw'></i>"
    weight = -120
[[menu.docs]]
    name = "Getting started"
    identifier = "getting-started"
    pre = "<i class='fa fa-road fa-fw'></i>"
    weight = -115
[[menu.docs]]
    name = "Deploying apps"
    identifier = "apps"
    pre = "<i class='fa fa-file-text fa-fw'></i>"
    weight = -110
[[menu.docs]]
    name = "Services"
    identifier = "services"
    pre = "<i class='fa fa-fw fa-database'></i>"
    weight = -100
[[menu.docs]]
    name = "Managing apps"
    identifier = "advanced"
    pre = "<i class='fa fa-rocket fa-fw'></i>"
    weight = -100
[[menu.docs]]
    name = "Compliance"
    identifier = "compliance"
    pre = "<i class='fa fa-check-square-o fa-fw'></i>"
    weight = -95
[[menu.docs]]
    name = "Experimental features"
    identifier = "experimental"
    pre = "<i class='fa fa-flask fa-fw'></i>"
    weight = -90
[[menu.docs]]
    name = "Team Documentation"
    identifier = "ops"
    pre = "<i class='fa fa-fw fa-wrench'></i>"
[[menu.docs]]
    name = "Deployment"
    identifier = "deployment"
    parent = "ops"
[[menu.docs]]
    name = "Tenant support"
    identifier = "tenants"
    parent = "ops"
[[menu.docs]]
    name = "Operations"
    identifier = "operations"
    parent = "ops"
[[menu.docs]]
    name = "Runbook"
    identifier = "runbook"
    parent = "ops"
[[menu.docs]]
    name = "Plans and policies"
    identifier = "policies"
    parent = "ops"
[[menu.docs]]
    name = "Design considerations"
    identifier = "design"
    parent = "ops"