platform: linux	
image_resource:	
  type: docker-image	
  source:	
    repository: node	
    tag: "10.1"	
inputs:	
- name: cg-site-source	
outputs:	
- name: cg-site-compiled	
run:	
  dir: cg-site-source	
  path: ci/build.sh
